[project]
name = "er-system"
version = "0.0.1"
description = "A pluggable entity resolution system for data transformation pipelines"
authors = [
    { name = "meaningfy.ws", email = "hi@meaningfy.ws" }
]
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "pydantic (>=2.10.6,<3.0.0)",
]

[dependency-groups]
dev = [
    "linkml>=1.9.2,<2.0.0",
]
