name: transform UML model

env:
  CM_FILE_NAME: mwb_CM.xml
  XMI_SOURCE_DIR: resources/transformation/xmi_conceptual_model
  OUTPUT_DIR_LINKML: resources/transformation/linkML
  MODEL2OWL_CONFIG_DIR: resources/transformation/model2owl-config
  MODEL2OWL_DEFAULT_CONFIG: test/ePO-default-config
  MODEL2OWL_BRANCH: feature/linkml
  SAXON_URL: https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "resources/transformation/xmi_conceptual_model/**"
      - "resources/transformation/model2owl-config/**"

jobs:
  linkML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: get model2owl
        run: |
          git clone --branch ${{ env.MODEL2OWL_BRANCH }} https://github.com/meaningfy-ws/model2owl.git
          pwd

      - name: get-saxon
        run: |
          mkdir -p model2owl/saxon
          curl -L -o model2owl/saxon/saxon.jar "${{ env.SAXON_URL }}"
          echo "Saxon downloaded from Maven Central"

      - name: linkML transform step
        run: |

          echo "-------------------linkML transform---------------------------------"
          sed -i "s|${{ env.MODEL2OWL_DEFAULT_CONFIG }}|../${{ env.MODEL2OWL_CONFIG_DIR }}|g" model2owl/config-proxy.xsl
          cat model2owl/config-proxy.xsl

          CM_FILE_PATH="${{ env.XMI_SOURCE_DIR }}/${{ env.CM_FILE_NAME }}"
          OUTPUT_PATH_LINKML="${{ env.OUTPUT_DIR_LINKML }}/"

          ls -la ${{ env.XMI_SOURCE_DIR }}/
          echo "CM_FILE_PATH is $CM_FILE_PATH"
          echo "OUTPUT_PATH_LINKML is $OUTPUT_PATH_LINKML"

          cd model2owl
          ls -la
          echo "+++++++++++++++++transform to linkML ++++++++++++++++++++++++++++"
          make linkML XMI_INPUT_FILE_PATH=../$CM_FILE_PATH OUTPUT_FOLDER_PATH=../$OUTPUT_PATH_LINKML
          echo "-------------------end transform---------------------------------"

          sed -i "s|../${{ env.MODEL2OWL_CONFIG_DIR }}|${{ env.MODEL2OWL_DEFAULT_CONFIG }}|g" config-proxy.xsl
          cd ..

        shell: bash

      - name: remove unnecessary files
        run: |
          sudo rm -rf model2owl
        shell: bash

      - name: commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git pull
          git status

          git add .
          if [ -z "$(git status --porcelain)" ]; then
          echo "push=false" >> $GITHUB_OUTPUT
          else
          git commit -m "[CI] UML->LinkML model2owl export #${{ github.run_number }}"
          echo "push=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
